### ISSUE TITLE
Failed to load a language-typescript package grammar

### ISSUE THREAD

**Issue by kiochan** [atom/language-typescript#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [language-typescript](https://github.com/atom/language-typescript) package 0.3.0-1

### Stack Trace

Failed to load a language-typescript package grammar

```
At Grammar missing required scopeName property: /Users/sunxingchen/.atom/packages/language-typescript/grammars/tree-sitter-flow.cson in /Users/sunxingchen/.atom/packages/language-typescript/grammars/tree-sitter-flow.cson

Error: Grammar missing required scopeName property: /Users/sunxingchen/.atom/packages/language-typescript/grammars/tree-sitter-flow.cson
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:123:70
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at /packages/language-typescript/grammars/tree-sitter-flow.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-html-preview 0.2.5 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
audio 1.5.7 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
coffee-navigator 0.0.18 
cson 2.0.1 
ex-mode 0.18.0 
git-control 0.9.0 
gitignore-snippets 0.2.5 
gitignores 0.3.2 
goto-definition 1.3.4 
graphviz-preview-plus 1.5.2 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
javascript-standard-snippets 0.2.1 
language-dot 1.7.0 
language-gitignore 0.3.0 
language-kagex 0.2.4 
language-lisp 0.2.0 
language-matlab 0.2.1 
language-tjs 0.6.2 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-coffees6 2.0.0 
linter-js-standard 4.1.0 
linter-markdown 5.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
pdf-view 0.61.0 
sequential-number 0.5.0 
simplified-chinese-menu 5.3.5 
sync-settings 0.8.3 
tab-numbers 0.6.1 
tree-view-copy-relative-path 1.2.0 
videoplayer 1.2.1 
vim-mode-plus 1.16.0 
```

**Comment by 50Wliu** [comment]
`language-typescript` is a bundled package and should not be installed manually.  Please uninstall it to use Atom's internal version instead.
