### ISSUE TITLE
Failed to load a language-typescript package grammar

### ISSUE THREAD

**Issue by wkdthf21** [atom/language-typescript#52]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [language-typescript](https://github.com/atom/language-typescript) package 0.6.2

### Stack Trace

Failed to load a language-typescript package grammar

```
At The specified module could not be found.
\\?\C:\Users\yesol\AppData\Local\atom\app-1.47.0\resources\app.asar.unpacked\node_modules\tree-sitter-typescript\build\Release\tree_sitter_tsx_binding.node in C:\Users\yesol\AppData\Local\atom\app-1.47.0\resources\app.asar\node_modules\language-typescript\grammars\tree-sitter-flow.json

Error: The specified module could not be found.
\\?\C:\Users\yesol\AppData\Local\atom\app-1.47.0\resources\app.asar.unpacked\node_modules\tree-sitter-typescript\build\Release\tree_sitter_tsx_binding.node
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:146766)
    at /app.asar/node_modules/tree-sitter-typescript/tsx/index.js:2:20)
    at /app.asar/node_modules/tree-sitter-typescript/tsx/index.js:15:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:735013)
    at new TreeSitterGrammar (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:3220847)
    at GrammarRegistry.createGrammar (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:360231)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:360072
    at u (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:580740)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:581993
    at electron/js2c/asar.js:571:9
    at FSReqCallback.wrapper [as oncomplete] (fs.js:483:5)
  at /app.asar/node_modules/language-typescript/grammars/tree-sitter-flow.json:1:1
```

### Commands

```
     -1:11.4.0 markdown-preview-enhanced:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-preview-enhanced 0.17.8 
seti-icons 1.5.4 
```

**Comment by cemile-zacks** [comment]
> 
> 
> Hi, for me this error was thrown after Sophos detected parts of the package as a threat "Generic ML PUA detected"
> ![image](https://user-images.githubusercontent.com/57676015/84285536-41e7eb80-ab46-11ea-9521-fc9db79632f4.png)

I am having the same issue. Did you find a way to solve that error?

**Comment by datacore-rzlatkova** [comment]
No, it just happened again to me today when I was editing a different file in Atom.

**Comment by ewolvy** [comment]
Why is this marked as closed? I just installed Atom today on a Windows 10 with Sophos antivirus and had the same issue. Disabling the antivirus is not an option to me.

**Comment by Aerijo** [comment]
@ewolvy The issue says nothing about antivirus. It is the followup comments that indicate it might be relevant.

Secondly, if if it is an antivirus issue, I also don't see any value in opening it. If you can find an actual virus that's one thing, but if your antivirus is giving you false positives then that's an issue with the antivirus.

**Comment by mpapineau** [comment]
I had the same experience with Sophos Anti-virus.  After install of Atom I was getting an error, I went into Sophos and "Allow and Restore" the detected threat.  I then had to uninstall Atom and re-install to get rid of the error

**Comment by mpapineau** [comment]
> 
> 
> Why is this marked as closed? I just installed Atom today on a Windows 10 with Sophos antivirus and had the same issue. Disabling the antivirus is not an option to me.

@ewolvy I had the same experience with Sophos Anti-virus.  After install of Atom I was getting an error, I went into Sophos and "Allow and Restore" the detected threat.  I then had to uninstall Atom and re-install to get rid of the error

**Comment by nelsond143** [comment]
I'm getting the same issue as well. Also Sophos, sophos is detecting this as a PUA and removing it.

**Comment by XyLanar** [comment]
Why install virus protection like Sophos if you can't handle it?

Open Sophos and then click on 'My activity'.

Under New activity you will see the Generic ML PUA that Sophos blocked for the program atom.

You can then allow it and exclude it from Sophos's scans until the heading "Potentially unwanted application cleaned up" is replaced by "Potentially unwanted application confirmed and restored".

This will place an exception in Sophos and atom will no longer be scanned.

This way it should no longer show you the error message when you start atom the next time.

I hope I could help you.

**Comment by elizrawr** [comment]
I have also encountered this problem today using Sophos antivirus on Windows 10. This is my work computer as well.
